### ISSUE TITLE
External Graph Memory

### ISSUE THREAD

**Issue by MazenHamdi** [Majiker/STAR#10]
Hey, great work.
I have a couple of questions, currently I am trying to compare different architectures by changing the original STAR architecture (for example deleting the 2nd encoder, changing the number of heads/layers..) and now I want to get rid of the graph memory and see how it works, I want to know if GM is essential for the temporal aspect of the transformer? and is it even possible to talk about getting rid of the GM.
Thanks in advance

**Comment by cunjunyu** [comment]
Hi, thanks for your interest in our work.

GM serves to retain the effect imposed by those pedestrians who have left the scene but used to be present. Some workarounds may do the same thing. For example, regarding the pedestrian as a static point the moment when they disappear from the scene. 

Thank you.

**Comment by MazenHamdi** [comment]
Oh I see, thanks a lot, 
so I tried to compare the model with and without a GM, here are the results: 
with GM: ADE/FDE: 0.160/0.312
without GM: ADE/FDE: 0.129/0.231

does it make sense that the results without the GM are better ? or maybe because I didn't run enough training samples (because the models are stochastic)

**Comment by cunjunyu** [comment]
> does it make sense that the results without the GM are better? or maybe because I didn't run enough training samples (because the models are stochastic)

GM does not provide a very significant improvement. Because the model is stochastic, you may get a different result in each run. The reason why we use GM is that GM brings a slight improvement in the deterministic version. 

Thanks.

**Comment by Majiker** [comment]
> does it make sense that the results without the GM are better? or maybe because I didn't run enough training samples (because the models are stochastic)

GM does not provide a very significant improvement. Because the model is stochastic, you may get a different result in each run. The reason why we use GM is that GM brings a slight improvement in the deterministic version. 

Thanks.
