### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by MazenHamdi** [Majiker/STAR#11]
Hello, I loved the work, very well done,

I am not familiar with the dataSets that you used, so I tried to visualize it, I couldn't identify the pedestrian from the trajectory, I noticed in the head of the dataset number keep repeating, are they pedestrian indexes ? and the other rows, are they x and y of the trajectory ? 
Thanks a lot

**Comment by cunjunyu** [comment]
<img width="566" alt="Screen Shot 2021-06-06 at 2 03 53 PM" src="https://user-images.githubusercontent.com/62012984/120914316-0a1b7180-c6d0-11eb-9ca6-a1fc1e148525.png">

First Row: Timestamp
Second Row: Pedestrian Indices
Third Row: X coordinate
Fourth Row: Y coordinate

Thanks.

**Comment by cunjunyu** [comment]
I will close the issue for now. Feel free to reopen it if you have any further questions.

**Comment by MazenHamdi** [comment]
What did you use the functions (find_trajectory_fragment, get_seq_from_index_balance, load_dict .etc) ? they are not used in the training nor the test, I deleted them and the model works just fine.

**Comment by cunjunyu** [comment]
They are used to generate training/testing datasets. The model still works because you have already generated the pickle file of the dataset when you first ran the code. see here
https://github.com/Majiker/STAR/blob/d2dd113e3deb1098760c454ab15e7cb0652f3c0c/src/utils.py#L65

Thank you.

**Comment by MazenHamdi** [comment]
About the dataset, is the pedestrian in hotel with index 1 the same pedestrian in the univ with the same index ?

**Comment by cunjunyu** [comment]
No, they are not. Hotel and Univ are two datasets collected at different places on different dates.

**Comment by MazenHamdi** [comment]
what exactly do you mean by "window"  ?
(sorry for all these questions, I am really interested in this work and I want to understand every single line of code)

**Comment by cunjunyu** [comment]
'window' refers to a time period which is normally 20 frames (8 for observation and 12 for prediction)
