### ISSUE TITLE
convert the norm value into the real prediction value

### ISSUE THREAD

**Issue by ycl204432** [Majiker/STAR#15]
Hello, I appreciate your project code and I would like to ask a question. The output of the model is after norm, when we do visualization we need to get the specific prediction value, how can we convert the norm value into the real prediction value?

**Comment by cunjunyu** [comment]
Thanks for your interest. 

Simply add it back to the coordinate of the last observation frame.

**Comment by ycl204432** [comment]
Wow, thank you very much for your quick reply!

**Comment by cunjunyu** [comment]
I will close the issue for now, please feel free to reopen it if you have any further questions.

**Comment by ycl204432** [comment]
Thank you very much for your reply. Finally ，I would like to ask you a question, is the last observation frame of the model fixed? In other words, is the last observation frame unique? Because the architecture of the code is single-step prediction.

**Comment by cunjunyu** [comment]
No. The last observation frame is not fixed. You need a series of observation frames to predict future trajectories. The last observation frame is basically the last frame of the input for prediction.

**Comment by ycl204432** [comment]
Wow so that's it, thank you very much for your patient answer!

**Comment by ycl204432** [comment]
Hi, I try to plot the curve in Fig.5(b):
![image](https://user-images.githubusercontent.com/47931982/187056514-d1a9335d-66cc-4bd0-b254-359dfb09a941.png)
But I get the following curve, which is not similar to the above curve:

![star-0](https://user-images.githubusercontent.com/47931982/187056535-6a0e1988-e2c7-461e-a31d-cdd8bcf09d35.png)

The inference codes are as following, which are modified from 
https://github.com/Majiker/STAR/blob/d2dd113e3deb1098760c454ab15e7cb0652f3c0c/src/processor.py#L154

```python
with torch.no_grad():
    self.dataloader.reset_batch_pointer(set='test')
    self.load_model()
    self.net.eval()
    idx = 0
    self.net.zero_grad()
    plt.figure()
    import tqdm

    for batch in tqdm.trange(self.dataloader.testbatchnums):
        inputs, batch_id = self.dataloader.get_test_batch(batch)
        inputs = tuple([torch.Tensor(i) for i in inputs])

        batch_abs, batch_norm, shift_value, seq_list, nei_list, nei_num, batch_pednum = inputs
        inputs_forward = batch_abs[:-1], batch_norm[:-1], shift_value[:-1], seq_list[:-1], nei_list[
                                                                                           :-1], nei_num[
                                                                                                 :-1], batch_pednum

        for i in range(batch_norm.size()[1]):
            if (idx == 6180):
                all_output = []
                for l in range(self.args.sample_num):
                    
                    outputs_infer = self.net.forward(inputs_forward, iftest=True)
                    all_output.append(outputs_infer)

                all_output = torch.stack(all_output)
                all_output = all_output[:, 7:]
                lossmask, num = getLossMask(all_output, seq_list[0], seq_list, using_cuda=self.args.using_cuda)

                pred_abs = all_output + shift_value[0]

                for q in range(20):
                    t = batch_abs[:8, i, 1:]
                    x = batch_abs[:8, i, :1]
                    plt.plot(x, t, marker='o', color='orange')
                    plt.plot(batch_abs[8:, i, :1], batch_abs[8:, i, 1:], marker='o', color='red')

                    plt.plot(pred_abs[q, :, i, 0], pred_abs[q, :, i, 1], marker='o', color='blue')
                    plt.xlim(3.5, 8)
                    plt.ylim(-1, 14)
                    plt.savefig(f'./imag/eth/star-{q}.png')
                    plt.clf()
                exit()

            idx += 1
```

**Comment by ycl204432** [comment]
Do I make some mistakes in inference codes?
