### ISSUE TITLE
About the model type

### ISSUE THREAD

**Issue by FindTheAnswer** [Majiker/STAR#2]
Hi, what is the difference between Deterministic model and Stochastic model? And what should I do to change the Deterministic version to  Stochastic version?

**Comment by Majiker** [comment]
The deterministic model predicts a single result, while the stochastic model generates a prediction of distribution. 

To convert a deterministic model to a stochastic version, one simple approach would be to introduce Gaussian noise when generating predictions and sample from the distribution.

**Comment by FindTheAnswer** [comment]
> The deterministic model predicts a single result, while the stochastic model generates a prediction of distribution.
> 
> To convert a deterministic model to a stochastic version, one simple approach would be to introduce Gaussian noise when generating predictions and sample from the distribution.

Many thanks! And to convert a stochastic version to a deterministic version, I should throw away Gaussian noise when training  and generating predictions or just when generating predictions?

**Comment by Majiker** [comment]
You are most welcome. 

Yes, you should train the model without Gaussian noise.

However, for this repo, we only provide the stochastic version of STAR. The hyperparameters of the deterministic version and the stochastic version can be quite different.

**Comment by FindTheAnswer** [comment]
> You are most welcome.
> 
> Yes, you should train the model without Gaussian noise.
> 
> However, for this repo, we only provide the stochastic version of STAR. The hyperparameters of the deterministic version and the stochastic version can be quit

**Comment by FindTheAnswer** [comment]
> You are most welcome.
> 
> Yes, you should train the model without Gaussian noise.
> 
> However, for this repo, we only provide the stochastic version of STAR. The hyperparameters of the deterministic version and the stochastic version can be quite different.

Have you considered releasing the deterministic version？

**Comment by Majiker** [comment]
We currently have no plan to release it since I'm quite occupied with other stuff.

However, we may try to release it once I have more free time to deal with it.

**Comment by FindTheAnswer** [comment]
> We currently have no plan to release it since I'm quite occupied with other stuff.
> 
> However, we may try to release it once I have more free time to deal with it.

Thanks again!
