### ISSUE TITLE
About TGConv

### ISSUE THREAD

**Issue by MinamiKotoka** [Majiker/STAR#3]
Hi, I'm interested in your work, but I can not find where the TGConv is in your code. Could you help me? Thank you very much.

**Comment by Yusufma03** [comment]
Hi, thanks for your interest in our work! In our implementation, we use a Transformer model with masks to impelment TGConv. For nodes with distance more than a threshold, we remove it by a mask during self-attention. You can find more details [here](https://github.com/Majiker/STAR/blob/194d34588c7e48564bee19257cd28b1426016b65/src/star.py#L305).
