### ISSUE TITLE
skip=6

### ISSUE THREAD

**Issue by ycl204432** [Majiker/STAR#7]
Hello, the author,

Thank you very much for sharing the code of this project.
 There is a problem I don't understand. I'd like to ask you. 
As for why in eth scenario, when testing the performance of ETH scenario, skip = 6. In this way, there is no way to use the mode of 8-step predict 12 step to realize the experiment of 3.2s predict 4.8s . It should take 20 steps to predict the position of 4.8s. I'd like to hear your opinion。

**Comment by cunjunyu** [comment]
We follow the data preprocessing from [sr-lstm](https://github.com/zhangpur/SR-LSTM) and the reason is specified in this [paper](https://arxiv.org/abs/1903.02793)

Thank you

**Comment by ycl204432** [comment]
Thank you very much for your reply. I've learned about it in my thesis.

Thank you very much

**Comment by cunjunyu** [comment]
I will close the issue for now, please feel free to reopen it if you have any further question.
