### ISSUE TITLE
About the Network structure of STAR

### ISSUE THREAD

**Issue by pavolusakruto** [Majiker/STAR#8]
Thank you for sharing!
In your STAR architecture, I found that the Spacial and Temporal Transformers are constructed parallelly in the first encoder, while serially in the second encoder. So why parallel? and why serial? 
Could you please tell us theory behind it?
Thank you!

**Comment by cunjunyu** [comment]
As we have communicated through email, I will close the issue for now.

**Comment by chenyouru** [comment]
I have the same question. Could you please tell me theory behind it?
